### ISSUE TITLE
Vesting Streams page isn't loading my contracts

### ISSUE THREAD

**Issue by protocoel** [LlamaPay/interface#97]
I have created a vesting contract, but it is not displaying because of some errors. 
Here are the errors. 
`Error: No provider
    at w (652-85d91643c68850a4.js:1:23773)
    at Object.queryFn (652-85d91643c68850a4.js:1:27808)
    at Object.l [as fn] (_app-e14ebcb262106091.js:6:208931)
    at _ (_app-e14ebcb262106091.js:22:29468)
    at c (_app-e14ebcb262106091.js:22:29861)
    at g.fetch (_app-e14ebcb262106091.js:6:209577)
    at l.executeFetch (_app-e14ebcb262106091.js:22:39339)
    at l.onSubscribe (_app-e14ebcb262106091.js:22:37212)
    at l.subscribe (_app-e14ebcb262106091.js:22:30154)
    at _app-e14ebcb262106091.js:22:46093
w @ 652-85d91643c68850a4.js:1
framework-73b8966a3c579ab0.js:9 `

`Uncaught Error: Minified React error #421; visit https://reactjs.org/docs/error-decoder.html?invariant=421 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at framework-73b8966a3c579ab0.js:9:78090
    at ub (framework-73b8966a3c579ab0.js:9:78364)
    at i (framework-73b8966a3c579ab0.js:9:121364)
    at oO (framework-73b8966a3c579ab0.js:9:99114)
    at framework-73b8966a3c579ab0.js:9:98981
    at oF (framework-73b8966a3c579ab0.js:9:98988)
    at oC (framework-73b8966a3c579ab0.js:9:96074)
    at r4 (framework-73b8966a3c579ab0.js:9:44778)
    at framework-73b8966a3c579ab0.js:9:93632
the-graph.kava.io/subgraphs/name/nemusonaneko/llamapay-subgraph/:1`          

`Failed to load resource: the server responded with a status of 404 ()
652-85d91643c68850a4.js:1`

`Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (data="0x", transaction={"to":"0x80C7DD17B01855a6D2347444a0FCC36136a314de","data":"0x399542e90000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000c8000000000000000000000000000000000000000000000000000000000000190000000000000000000000000000000000000000000000000000000000000019a00000000000000000000000000000000000000000000000000000000000001a400000000000000000000000000000000000000000000000000000000000001ae00000000000000000000000000000000000000000000000000000000000001b800000000000000000000000000000000000000000000000000000000000001c200000000000000000000000000000000000000000000000000000000000001cc00000000000000000000000000000000000000000000000000000000000001d600000000000000000000000000000000000000000000000000000000000001e000000000000000000000000000000000000000000000000000000000000001ea00000000000000000000000000000000000000000000000000000000000001f400000000000000000000000000000000000000000000000000000000000001fe00000000000000000000000000000000000000000000000000000000000002080000000000000000000000000000000000000000000000000000000000000212000000000000000000000000000000000000000000000000000000000000021c00000000000000000000000000000000000000000000000000000000000002260000000000000000000000000000000000000000000000000000000000000230000000000000000000000000000000000000000000000000000000000000023a0000000000000000000000000000000000000000000000000000000000000244000000000000000000000000000000000000000000000000000000000000024e00000000000000000000000000000000000000000000000000000000000002580000000000000000000000000000000000000000000000000000000000000262000000000000000000000000000000000000000000000000000000000000026c00000000000000000000000000000000000000000000000000000000000002760000000000000000000000000000000000000000000000000000000000000280000000000000000000000000000000000000000000000000000000000000028a0000000000000000000000000000000000000000000000000000000000000294000000000000000000000000000000000000000000000000000000000000029e00000000000000000000000000000000000000000000000000000000000002a800000000000000000000000000000000000000000000000000000000000002b200000000000000000000000000000000000000000000000000000000000002bc00000000000000000000000000000000000000000000000000000000000002c600000000000000000000000000000000000000000000000000000000000002d000000000000000000000000000000000000000000000000000000000000002da00000000000000000000000000000000000000000000000000000000000002e400000000000000000000000000000000000000000000000000000000000002ee00000000000000000000000000000000000000000000000000000000000002f80000000000000000000000000000000000000000000000000000000000000302000000000000000000000000000000000000000000000000000000000000030c00000000000000000000000000000000000000000000000000000000000003160000000000000000000000000000000000000000000000000000000000000320000000000000000000000000000000000000000000000000000000000000032a0000000000000000000000000000000000000000000000000000000000000334000000000000000000000000000000000000000000000000000000000000033e00000000000000000000000000000000000000000000000000000000000003480000000000000000000000000000000000000000000000000000000000000352000000000000000000000000000000000000000000000000000000000000035c00000000000000000000000000000000000000000000000000000000000003660000000000000000000000000000000000000000000000000000000000000370000000000000000000000000000000000000000000000000000000000000037a0000000000000000000000000000000000000000000000000000000000000384000000000000000000000000000000000000000000000000000000000000038e000000000000000000000000000000000000000000000000000000000000039800000000000000000000000000000000000000000000000000000000000003a200000000000000000000000000000000000000000000000000000000000003ac00000000000000000000000000000000000000000000000000000000000003b600000000000000000000000000000000000000000000000000000000000003c000000000000000000000000000000000000000000000000000000000000003ca00000000000000000000000000000000000000000000000000000000000003d400000000000000000000000000000000000000000000000000000000000003de00000000000000000000000000000000000000000000000000000000000003e800000000000000000000000000000000000000000000000000000000000003f200000000000000000000000000000000000000000000000000000000000003fc00000000000000000000000000000000000000000000000000000000000004060000000000000000000000000000000000000000000000000000000000000410000000000000000000000000000000000000000000000000000000000000041a0000000000000000000000000000000000000000000000000000000000000424000000000000000000000000000000000000000000000000000000000000042e00000000000000000000000000000000000000000000000000000000000004380000000000000000000000000000000000000000000000000000000000000442000000000000000000000000000000000000000000000000000000000000044c0000000000000000000000    at p.makeError (_app-e14ebcb262106091.js:1:105330)
    at p.throwError (_app-e14ebcb262106091.js:1:105444)
    at v (_app-e14ebcb262106091.js:1:185763)
    at k.<anonymous> (_app-e14ebcb262106091.js:1:195028)
    at Generator.throw (<anonymous>)
    at a (_app-e14ebcb262106091.js:1:185110)`

The screen displays the Fallback component. 
![image](https://user-images.githubusercontent.com/125755135/219878156-c6245893-6692-404b-9985-65f57ea14092.png)

I guess the relevant file is: https://github.com/LlamaPay/interface/blob/main/components/Vesting/index.tsx

**Comment by mintdart** [comment]
@Nemusonaneko
